# Generated by Django 5.2.4 on 2025-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_nom_customuser_prenom_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testautomatique',
            name='emails_notification',
            field=models.JSONField(blank=True, default=list, help_text='Liste des emails pour recevoir les notifications'),
        ),
    ]
